### ISSUE TITLE
Logging on CCS side is not sufficient

### ISSUE THREAD

**Issue by calmnesss** [openremote/CCS#20]
Logging on CCS side is missing to cover several crucial operations:
 - adding websocket connection
 - removing websocket connection

This makes it hard to analyze actual issues on production side. For example without them it is impossible to say what is causing Issue#19.

It is required to:
1) log these crucial parts of the system and add Beehive account username to the logs to be able at least to diffirentiate logs between multiple accounts.
2) Update existing log messages related to command processing to include Beehive account username.

**Comment by mickz18** [comment]
I have pushed some improvement, please let me know if it's ok like that or your see some missing part where you would like to have more logging.

**Comment by calmnesss** [comment]
Looks good, but I need to check woth production team regarding log levels

**Comment by calmnesss** [comment]
Can we have log level for open/close WS session set to INFO?

**Comment by calmnesss** [comment]
Integrated
